"""empty message

Revision ID: 07ce34452bdc
Revises: c3b99cb248f5
Create Date: 2026-01-05 13:36:10.056098

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "07ce34452bdc"
down_revision = "c3b99cb248f5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_attribute",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "task_completion",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("point_change", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["task.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###

    # Create trigger to update balance on task completion insert
    # pre-seed the balance attribute
    op.execute("""
    INSERT INTO user_attribute (key, value) VALUES ('balance', '0')
    ON CONFLICT(key) DO NOTHING;
    """)

    op.execute("""
    CREATE TRIGGER task_completion_balance_update
    AFTER INSERT ON task_completion
    BEGIN
        UPDATE user_attribute
        SET value = CAST(COALESCE(CAST(value AS INTEGER), 0) + NEW.point_change AS TEXT)
        WHERE key = 'balance';
    END;""")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task_completion")
    op.drop_table("user_attribute")
    # ### end Alembic commands ###

    op.execute("DROP TRIGGER IF EXISTS task_completion_balance_update;")
